/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.Appt;

import javax.swing.*;
import models.Appt;
import controller.ApptServiceController;
import controller.CustomerController;
import controller.TechnicianController;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 *
 * @author GENJI
 */
public class AddApt extends javax.swing.JFrame {

    private final ApptServiceController apptService; 
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
    /**
     * Creates new form AddApt
     */
    public AddApt() {
        ArrayList<HashMap<String, Object>> allTechnicians;
        ArrayList<HashMap<String, Object>> allCustomers;
        TechnicianController technicianController = new TechnicianController();
        allTechnicians = technicianController.getAllTechnicianList();
        String [] technicianModel = new String[allTechnicians.size()];
        CustomerController customerController = new CustomerController();
        allCustomers = customerController.getAllCustomerList();
        String [] customerModel = new String[allCustomers.size()];
        
        
        for(int x = 0;x < allTechnicians.size();x++)
        {
            technicianModel[x] = allTechnicians.get(x).get("username").toString();
        }
        
        for(int x = 0;x < allCustomers.size();x++)
        {
            customerModel[x] = allCustomers.get(x).get("username").toString();
        }
        
        initComponents();
        this.apptService = new ApptServiceController();
        cbxAddApptCustomerName.setModel(new javax.swing.DefaultComboBoxModel<>(customerModel));
        cbxAddApptTechnician.setModel(new javax.swing.DefaultComboBoxModel<>(technicianModel));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comfirmpaymentbutton = new javax.swing.JButton();
        apptNameField = new javax.swing.JTextField();
        apptDateField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        apptTimeField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        apptFeedbackField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        apptServiceTypeField = new javax.swing.JComboBox<>();
        apptPaymentStatusField = new javax.swing.JComboBox<>();
        apptAmountField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxAddApptCustomerName = new javax.swing.JComboBox<>();
        cbxAddApptTechnician = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(145, 255, 167));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Appointment");

        jPanel3.setBackground(new java.awt.Color(255, 165, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Technician :");

        comfirmpaymentbutton.setText("SUBMIT");
        comfirmpaymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmpaymentbuttonActionPerformed(evt);
            }
        });

        apptNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apptNameFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Date :");

        jLabel6.setText("Time :");

        jLabel7.setText("Service Type :");

        apptTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apptTimeFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Payment Status :");

        jLabel10.setText("Name :");

        jLabel4.setText("Customer Name :");

        jLabel8.setText("FeedBack :");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        apptServiceTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room Cleaning", "Bed Linen Change", "Breakfast", "Laundry", "Tour Guide" }));
        apptServiceTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apptServiceTypeFieldActionPerformed(evt);
            }
        });

        apptPaymentStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Success", "Failed" }));

        apptAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apptAmountFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Amount :");

        cbxAddApptCustomerName.setPreferredSize(new java.awt.Dimension(73, 22));

        cbxAddApptTechnician.setPreferredSize(new java.awt.Dimension(73, 22));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comfirmpaymentbutton)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxAddApptTechnician, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxAddApptCustomerName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apptDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(apptNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(apptTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(apptServiceTypeField, 0, 224, Short.MAX_VALUE)
                            .addComponent(apptFeedbackField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(apptAmountField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(apptPaymentStatusField, 0, 224, Short.MAX_VALUE))
                        .addGap(128, 128, 128))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {apptAmountField, apptDateField, apptFeedbackField, apptNameField, apptPaymentStatusField, apptServiceTypeField, apptTimeField});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(apptNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(apptDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(apptTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(apptServiceTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(apptAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apptPaymentStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(cbxAddApptCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbxAddApptTechnician, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apptFeedbackField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comfirmpaymentbutton)
                    .addComponent(backButton))
                .addGap(35, 35, 35))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {apptAmountField, apptDateField, apptFeedbackField, apptNameField, apptPaymentStatusField, apptServiceTypeField, apptTimeField});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isValidDate(String date) {
        dateFormat.setLenient(false);
        try {
            dateFormat.parse(date);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    private boolean isValidTime(String time) {
        // Validate time format
        if (!time.matches("\\d{2}:\\d{2}(AM|PM|am|pm)")) {
            return false; // Invalid format
        }
        return true;
    }
    
    private boolean isDuplicateName(String name) {
        try {
            List<String> lines = Files.readAllLines(Paths.get("storage/appointment.txt"));
            for (String line : lines) {
                // Split the line to extract the appointment name
                String[] parts = line.split(",");
                String existingName = parts[0]; // Assuming the name is the first column

                // Check if the name already exists
                if (existingName.equals(name)) {
                    return true; // Found a duplicate name
                }
            }
        } catch (IOException e) {
            e.printStackTrace(); // Handle or log the error
        }
        return false; // No duplicate names found
    }
    
    private void comfirmpaymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmpaymentbuttonActionPerformed

        String name = apptNameField.getText();
        String date = apptDateField.getText();
        String time = apptTimeField.getText();
        String feedback = apptFeedbackField.getText();
        String amount = apptAmountField.getText();
        String paymentStatus = (String) apptPaymentStatusField.getSelectedItem();
        String selectedServiceType = (String) apptServiceTypeField.getSelectedItem();
        String technicianName = cbxAddApptTechnician.getSelectedItem().toString();
        String customerName = cbxAddApptCustomerName.getSelectedItem().toString();
        System.out.println(technicianName);
        System.out.println(customerName);
        
        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Appointment name cannot be empty");
            return;
        }
        
        if (isDuplicateName(name)) {
            JOptionPane.showMessageDialog(this, "An appointment with the same name already exists");
            return;
        }
        
        if(amount.isEmpty() || !amount.chars().allMatch( Character::isDigit) ||
                Double.parseDouble(amount) <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid amount for the item");
            return;
        }
        
        if (date.isEmpty() || !date.matches("\\d{4}-\\d{2}-\\d{2}") || !isValidDate(date)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid date for the appointment");
            return;
        }
        
        if (time.isEmpty() || !isValidTime(time)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid time for the appointment");
            return;
        }
        
        if(customerName.isEmpty() ) {
            customerName = null;
            
        }
        
        if(technicianName.isEmpty() ) {
            technicianName = null;
            
        }
        
        if(feedback.isEmpty() ) {
            feedback = null;
            
        }
        
        Appt appt = new Appt(name,date,time,selectedServiceType,Double.parseDouble(apptAmountField.getText()),paymentStatus,technicianName,customerName,feedback);
        
        apptService.create(appt);
      
        apptNameField.setText("");
        apptFeedbackField.setText("");
        apptAmountField.setText("");
        apptServiceTypeField.setSelectedItem("");
        apptDateField.setText("");
        apptTimeField.setText("");
        apptPaymentStatusField.setSelectedItem("");
        JOptionPane.showMessageDialog(this, "Appointment has been added");
    }//GEN-LAST:event_comfirmpaymentbuttonActionPerformed

    private void apptNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apptNameFieldActionPerformed

    private void apptTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apptTimeFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ApptManagement im = new ApptManagement();
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void apptServiceTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptServiceTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apptServiceTypeFieldActionPerformed

    private void apptAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apptAmountFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddApt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apptAmountField;
    private javax.swing.JTextField apptDateField;
    private javax.swing.JTextField apptFeedbackField;
    private javax.swing.JTextField apptNameField;
    private javax.swing.JComboBox<String> apptPaymentStatusField;
    private javax.swing.JComboBox<String> apptServiceTypeField;
    private javax.swing.JTextField apptTimeField;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> cbxAddApptCustomerName;
    private javax.swing.JComboBox<String> cbxAddApptTechnician;
    private javax.swing.JButton comfirmpaymentbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
