/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ApptServiceController;
import javax.swing.JOptionPane;
import javax.swing.*;
import models.Biling;
import controller.BillingServiceController;
import controller.TechnicianController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import models.Appt;
/**
 *
 * @author GENJI
 */
public class BillingManagement extends javax.swing.JFrame {
    
    private final BillingServiceController bilingService;
    private final ApptServiceController apptService;
    private static Map<String, String[]> detailsMap = new HashMap<>();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
    private int loggedTechID;
    /**
     * Creates new form BillingManagement
     */
    public BillingManagement(int techid) {
        initComponents();
        this.bilingService = new BillingServiceController();
        this.apptService = new ApptServiceController();
        performFileRelatedTask(techid);
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comfirmpaymentbutton = new javax.swing.JButton();
        DATEFIELD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AMOUNTFIELD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BANKNAMEFIELD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RECIPIENTFIELD = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        NAMEFIELD = new javax.swing.JTextField();
        APPTNAMEFIELD = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        mTime = new javax.swing.JTextField();
        mTechnician = new javax.swing.JTextField();
        mServiceType = new javax.swing.JComboBox<>();
        mCustomerName = new javax.swing.JTextField();
        mFeedback = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PAYMENT");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Name :");

        comfirmpaymentbutton.setText("SUBMIT");
        comfirmpaymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmpaymentbuttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Date :");

        jLabel7.setText("Amount :");

        AMOUNTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMOUNTFIELDActionPerformed(evt);
            }
        });

        jLabel10.setText("Appointment name:");

        jLabel4.setText("Bank Name:");

        jLabel8.setText("Recipient :");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        NAMEFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEFIELDActionPerformed(evt);
            }
        });

        APPTNAMEFIELD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        APPTNAMEFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APPTNAMEFIELDActionPerformed(evt);
            }
        });

        mTime.setBackground(new java.awt.Color(204, 204, 204));
        mTime.setForeground(new java.awt.Color(204, 204, 204));
        mTime.setCaretColor(new java.awt.Color(204, 204, 204));
        mTime.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        mTime.setSelectedTextColor(new java.awt.Color(204, 204, 204));

        mServiceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room Cleaning", "Bed Linen Change", "Breakfast", "Laundry", "Tour Guide" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mTechnician, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mTechnician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DATEFIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(AMOUNTFIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(APPTNAMEFIELD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BANKNAMEFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RECIPIENTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NAMEFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comfirmpaymentbutton)
                        .addGap(39, 39, 39))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AMOUNTFIELD, APPTNAMEFIELD, BANKNAMEFIELD, DATEFIELD, NAMEFIELD, RECIPIENTFIELD, jLabel10, jLabel3, jLabel4, jLabel5, jLabel7, jLabel8});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APPTNAMEFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATEFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AMOUNTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NAMEFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BANKNAMEFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RECIPIENTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comfirmpaymentbutton)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AMOUNTFIELD, APPTNAMEFIELD, BANKNAMEFIELD, DATEFIELD, NAMEFIELD, RECIPIENTFIELD, jLabel10, jLabel3, jLabel4, jLabel5, jLabel7, jLabel8});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void performFileRelatedTask(int techid) {
        loggedTechID = techid;
        TechnicianController managerController = new TechnicianController();
        HashMap<String, Object> techDeatils = managerController.getTechnicianDetails(loggedTechID);
        APPTNAMEFIELD.removeAllItems();
        APPTNAMEFIELD.addItem("");
        String[] columnNames = {"Name", "Date", "Time", "Service Type", "Amount", "Payment Status", "Technician Name", "Customer Name", "Feedback"};
         // Create DefaultTableModel with column names
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        apptService.getAll().forEach((appt) -> {
            model.addRow(new Object[]{
                appt.getName(),
                appt.getDate(),
                appt.getTime(),
                appt.getServiceType(),
                appt.getAmount(),
                appt.getPaymentStatus(),
                appt.getTechnician(),
                appt.getCustomerName(),
                appt.getFeedback()
            });
        });
        
        try {
            // Read all lines from the file into a list
            for (String line : Files.readAllLines(Paths.get("storage/appointment.txt"))) {
                String[] parts = line.split(",");
                if (parts.length > 0) {
                    String name = parts[0];
                    String techname = parts[6];
                    String paymentStatus = parts[5];
                    if(techname.equals(techDeatils.get("username").toString()) && !paymentStatus.equals("Success")){
                       APPTNAMEFIELD.addItem(name);
                       detailsMap.put(name, parts);
                    }                                    
                }
            }
        } catch (IOException e) {
            e.printStackTrace(); // Handle or log the error
        }
        
        APPTNAMEFIELD.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JComboBox<String> source = (JComboBox<String>) e.getSource();
                String selectedName = (String) source.getSelectedItem();
                if (selectedName != null) {
                    // Retrieve details from the map based on the selected name
                    String[] details = detailsMap.get(selectedName);
                    if (details != null) {
                        // Auto-fill other text fields                 
                        DATEFIELD.setText(details[1]);  
                        AMOUNTFIELD.setText(details[4]);
                        
                         
                        mTime.setText(details[2]); 
                        mServiceType.setSelectedItem(details[3]);                       
                        mTechnician.setText(details[6]); 
                        mCustomerName.setText(details[7]); 
                        mFeedback.setText(details[8]);
                        
                        
                        
                    }
                }
            }
        });
    }
    private void APPTNAMEFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APPTNAMEFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APPTNAMEFIELDActionPerformed

    private void NAMEFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEFIELDActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        TechnicianDashboard td = new TechnicianDashboard(loggedTechID);
        td.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void AMOUNTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMOUNTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMOUNTFIELDActionPerformed

    private void comfirmpaymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmpaymentbuttonActionPerformed
        TechnicianController managerController = new TechnicianController();
        HashMap<String, Object> techDeatils = managerController.getTechnicianDetails(loggedTechID);
        String appt_name = APPTNAMEFIELD.getSelectedItem().toString();
        String date = DATEFIELD.getText();
        String amount = AMOUNTFIELD.getText();
        String name = NAMEFIELD.getText();
        String bankname = BANKNAMEFIELD.getText();
        String recipient = RECIPIENTFIELD.getText();
        
       
        String time = mTime.getText();
        String feedback = mFeedback.getText();
        
        String selectedServiceType = (String) mServiceType.getSelectedItem();
        String technicianName = mTechnician.getText();
        String customerName = mCustomerName.getText();
        //Appointment
//        String paymentStatus = "active";

        if(appt_name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Appointment Name cannot be empty");
            return;
        }

        if(date.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date cannot be empty");
            return;
        }

        if(!amount.isEmpty()){
            if (!amount.matches("\\d+(\\.\\d+)?")) {
                JOptionPane.showMessageDialog(this, "Please enter a valid amount for the appointment");
                return;
            }

            // Now, if the amount is in a valid format, check if it's <= 0
            if (Double.parseDouble(amount) <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid amount for the appointment");
                return;
            }
        }

        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name cannot be empty");
            return;
        }

        if(bankname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bank Name cannot be empty");
            return;
        }

        if(recipient.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Recipient cannot be empty");
            return;
        }

        Biling biling = new Biling(appt_name,date,Double.parseDouble(AMOUNTFIELD.getText()),name,bankname,recipient);

        bilingService.create(biling);
        
        Appt updatedAppt = new Appt(appt_name,date,time,selectedServiceType,Double.parseDouble(AMOUNTFIELD.getText()),"Success",technicianName,customerName,feedback);

        boolean isUpdated = apptService.update(appt_name, updatedAppt);
        APPTNAMEFIELD.removeAllItems();
        APPTNAMEFIELD.addItem("");
        APPTNAMEFIELD.setSelectedItem(null);
        DATEFIELD.setText("");
        AMOUNTFIELD.setText("");
        NAMEFIELD.setText("");
        BANKNAMEFIELD.setText("");
        RECIPIENTFIELD.setText("");
        
        try {
            // Read all lines from the file into a list
            for (String line : Files.readAllLines(Paths.get("storage/appointment.txt"))) {
                String[] parts = line.split(",");
                if (parts.length > 0) {
                    String aname = parts[0];
                    String techname = parts[6];
                    String paymentStatus = parts[5];
                    if(techname.equals(techDeatils.get("username").toString()) && !paymentStatus.equals("Success")){
                       APPTNAMEFIELD.addItem(aname);
                       detailsMap.put(name, parts);
                    }                                    
                }
            }
        } catch (IOException e) {
            e.printStackTrace(); // Handle or log the error
        }
        
        if (!isUpdated) {
            JOptionPane.showMessageDialog(this, "No appointment name was found to updated.");
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Billing has been added");
        TechnicianDashboard td = new TechnicianDashboard(loggedTechID);
        td.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_comfirmpaymentbuttonActionPerformed

    private void performFileRelatedTask() {
        APPTNAMEFIELD.removeAllItems();
        APPTNAMEFIELD.addItem("");
        String[] columnNames = {"Name", "Date", "Time", "Service Type", "Amount", "Payment Status", "Technician Name", "Customer Name", "Feedback"};
         // Create DefaultTableModel with column names
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        apptService.getAll().forEach((appt) -> {
            model.addRow(new Object[]{
                appt.getName(),
                appt.getDate(),
                appt.getTime(),
                appt.getServiceType(),
                appt.getAmount(),
                appt.getPaymentStatus(),
                appt.getTechnician(),
                appt.getCustomerName(),
                appt.getFeedback()
            });
        });
        
        try {
            // Read all lines from the file into a list
            for (String line : Files.readAllLines(Paths.get("storage/appointment.txt"))) {
                String[] parts = line.split(",");
                if (parts.length > 0) {
                    String name = parts[0];
                    APPTNAMEFIELD.addItem(name);
                    detailsMap.put(name, parts);
                }
            }
        } catch (IOException e) {
            e.printStackTrace(); // Handle or log the error
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new BillingManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMOUNTFIELD;
    private javax.swing.JComboBox<String> APPTNAMEFIELD;
    private javax.swing.JTextField BANKNAMEFIELD;
    private javax.swing.JTextField DATEFIELD;
    private javax.swing.JTextField NAMEFIELD;
    private javax.swing.JTextField RECIPIENTFIELD;
    private javax.swing.JButton backButton;
    private javax.swing.JButton comfirmpaymentbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mCustomerName;
    private javax.swing.JTextField mFeedback;
    private javax.swing.JComboBox<String> mServiceType;
    private javax.swing.JTextField mTechnician;
    private javax.swing.JTextField mTime;
    // End of variables declaration//GEN-END:variables
}
