/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.TechnicianController;
import java.util.HashMap;
//import view.ManagerDashboard;

/**
 *
 * @author User
 */
public class EditTechnicianAccount extends javax.swing.JFrame {
    private int technicianId;
    /**
     * Creates new form EditTechnicianAccount
     */
    public EditTechnicianAccount(int technicianId) {
        this.technicianId = technicianId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTechnicianNewUsername = new javax.swing.JLabel();
        tbxTechnicianCurrentPwd = new javax.swing.JTextField();
        lblTechnicianCurrentPwd = new javax.swing.JLabel();
        tbxTechnicianCurrentUsername = new javax.swing.JTextField();
        lblTechnicianCurrentUsername = new javax.swing.JLabel();
        lblTechnicianNewPwd = new javax.swing.JLabel();
        tbxTechnicianNewPwd = new javax.swing.JTextField();
        tbxTechnicianNewUsername = new javax.swing.JTextField();
        btnSaveEditTechnicianAcc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTechnicianNewUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTechnicianNewUsername.setText("New Username:");
        lblTechnicianNewUsername.setToolTipText("");
        lblTechnicianNewUsername.setPreferredSize(new java.awt.Dimension(200, 50));

        tbxTechnicianCurrentPwd.setEditable(false);
        tbxTechnicianCurrentPwd.setBackground(new java.awt.Color(255, 255, 255));

        lblTechnicianCurrentPwd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTechnicianCurrentPwd.setText("Current Password:");
        lblTechnicianCurrentPwd.setToolTipText("");
        lblTechnicianCurrentPwd.setPreferredSize(new java.awt.Dimension(200, 50));

        tbxTechnicianCurrentUsername.setEditable(false);
        tbxTechnicianCurrentUsername.setBackground(new java.awt.Color(255, 255, 255));

        lblTechnicianCurrentUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTechnicianCurrentUsername.setText("Current Username:");
        lblTechnicianCurrentUsername.setToolTipText("");
        lblTechnicianCurrentUsername.setPreferredSize(new java.awt.Dimension(200, 50));

        lblTechnicianNewPwd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTechnicianNewPwd.setText("New Password:");
        lblTechnicianNewPwd.setToolTipText("");
        lblTechnicianNewPwd.setPreferredSize(new java.awt.Dimension(200, 50));

        btnSaveEditTechnicianAcc.setText("Save");
        btnSaveEditTechnicianAcc.setPreferredSize(new java.awt.Dimension(200, 50));
        btnSaveEditTechnicianAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditTechnicianAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveEditTechnicianAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTechnicianNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTechnicianCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTechnicianNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTechnicianCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbxTechnicianCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxTechnicianCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxTechnicianNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxTechnicianNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTechnicianCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxTechnicianCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTechnicianCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxTechnicianCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTechnicianNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxTechnicianNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTechnicianNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxTechnicianNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSaveEditTechnicianAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveEditTechnicianAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditTechnicianAccActionPerformed
//        String inputtedUsername = tbxTechnicianNewUsername.getText();
//        String inputtedPassword = tbxTechnicianNewPwd.getText();
//        TechnicianController technicianController = new TechnicianController();
//        technicianController.editTechnicianAcc(LoggedInTechnicianid,inputtedUsername,inputtedPassword);
//        ManagerDashboard managerDashboard = new ManagerDashboard(currentTechnician);
//        managerDashboard.setVisible(true);
//        setVisible(false);
//        dispose();
    }//GEN-LAST:event_btnSaveEditTechnicianAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTechnicianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTechnicianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTechnicianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTechnicianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new EditTechnicianAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveEditTechnicianAcc;
    private javax.swing.JLabel lblTechnicianCurrentPwd;
    private javax.swing.JLabel lblTechnicianCurrentUsername;
    private javax.swing.JLabel lblTechnicianNewPwd;
    private javax.swing.JLabel lblTechnicianNewUsername;
    private javax.swing.JTextField tbxTechnicianCurrentPwd;
    private javax.swing.JTextField tbxTechnicianCurrentUsername;
    private javax.swing.JTextField tbxTechnicianNewPwd;
    private javax.swing.JTextField tbxTechnicianNewUsername;
    // End of variables declaration//GEN-END:variables
}
