/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.HashMap;
import view.EditCustomerAccount;
import controller.CustomerController;

/**
 *
 * @author User
 */
public class EditCustomerSelection extends javax.swing.JFrame {
    private int loggedInManagerid;
    private ArrayList<HashMap<String, Object>> allCustomers;
    /**
     * Creates new form EditCustomerSelection
     */
    public EditCustomerSelection(int managerId) {
        loggedInManagerid = managerId;
        CustomerController customerController = new CustomerController();
        allCustomers = customerController.getAllCustomerList();
        String [] customerModel = new String[allCustomers.size()];
        
        
        for(int x = 0;x < allCustomers.size();x++)
        {
            customerModel[x] = allCustomers.get(x).get("username").toString();
        }
        initComponents();
        combobxEditCustomerSelection.setModel(new javax.swing.DefaultComboBoxModel<>(customerModel));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditCustomerSelection = new javax.swing.JButton();
        combobxEditCustomerSelection = new javax.swing.JComboBox<>();
        lblEditCustomerSelection = new javax.swing.JLabel();
        lblLoginUsername1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEditCustomerSelection.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEditCustomerSelection.setText("Next");
        btnEditCustomerSelection.setPreferredSize(new java.awt.Dimension(200, 50));
        btnEditCustomerSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerSelectionActionPerformed(evt);
            }
        });

        combobxEditCustomerSelection.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combobxEditCustomerSelection.setPreferredSize(new java.awt.Dimension(200, 50));

        lblEditCustomerSelection.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEditCustomerSelection.setText("Select customer to edit:");
        lblEditCustomerSelection.setPreferredSize(new java.awt.Dimension(200, 50));

        lblLoginUsername1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblLoginUsername1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLoginUsername1.setText("Customer Selections");
        lblLoginUsername1.setAlignmentY(0.0F);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lblEditCustomerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobxEditCustomerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnEditCustomerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(lblLoginUsername1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(back)))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(lblLoginUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditCustomerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobxEditCustomerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnEditCustomerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(back)
                .addGap(246, 246, 246))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combobxEditCustomerSelection, lblEditCustomerSelection});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditCustomerSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerSelectionActionPerformed
        int selectedInd = combobxEditCustomerSelection.getSelectedIndex();
        EditCustomerAccount editCustomerAccount = new EditCustomerAccount(Integer.parseInt(allCustomers.get(selectedInd).get("id").toString()));
        editCustomerAccount.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnEditCustomerSelectionActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        ManagerDashboard md = new ManagerDashboard(loggedInManagerid);
        md.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new EditCustomerSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnEditCustomerSelection;
    private javax.swing.JComboBox<String> combobxEditCustomerSelection;
    private javax.swing.JLabel lblEditCustomerSelection;
    private javax.swing.JLabel lblLoginUsername1;
    // End of variables declaration//GEN-END:variables
}
