/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.CustomerController;
import controller.UserController;
import java.util.HashMap;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class EditCustomerAccount extends javax.swing.JFrame {
    private int customerId;
    /**
     * Creates new form EditCustomerAccount
     */
    public EditCustomerAccount(int customerId) {
        this.customerId = customerId;
        CustomerController customerController = new CustomerController();
        HashMap<String, Object> technicianDetails = customerController.getCustomerDetails(this.customerId);
        initComponents();
        tbxCustomerCurrentUsername.setText(technicianDetails.get("username").toString());
        tbxCustomerCurrentPwd.setText(technicianDetails.get("password").toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerCurrentPwd = new javax.swing.JLabel();
        tbxCustomerCurrentUsername = new javax.swing.JTextField();
        lblCustomerCurrentUsername = new javax.swing.JLabel();
        lblCustomerNewPwd = new javax.swing.JLabel();
        tbxCustomerNewPwd = new javax.swing.JTextField();
        tbxCustomerNewUsername = new javax.swing.JTextField();
        btnSaveEditCustomerAcc = new javax.swing.JButton();
        lblCustomerNewUsername = new javax.swing.JLabel();
        tbxCustomerCurrentPwd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerCurrentPwd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCustomerCurrentPwd.setText("Current Password:");
        lblCustomerCurrentPwd.setToolTipText("");
        lblCustomerCurrentPwd.setPreferredSize(new java.awt.Dimension(200, 50));

        tbxCustomerCurrentUsername.setEditable(false);
        tbxCustomerCurrentUsername.setBackground(new java.awt.Color(255, 255, 255));

        lblCustomerCurrentUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCustomerCurrentUsername.setText("Current Username:");
        lblCustomerCurrentUsername.setToolTipText("");
        lblCustomerCurrentUsername.setPreferredSize(new java.awt.Dimension(200, 50));

        lblCustomerNewPwd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCustomerNewPwd.setText("New Password:");
        lblCustomerNewPwd.setToolTipText("");
        lblCustomerNewPwd.setPreferredSize(new java.awt.Dimension(200, 50));

        btnSaveEditCustomerAcc.setText("Save");
        btnSaveEditCustomerAcc.setPreferredSize(new java.awt.Dimension(200, 50));
        btnSaveEditCustomerAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditCustomerAccActionPerformed(evt);
            }
        });

        lblCustomerNewUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCustomerNewUsername.setText("New Username:");
        lblCustomerNewUsername.setToolTipText("");
        lblCustomerNewUsername.setPreferredSize(new java.awt.Dimension(200, 50));

        tbxCustomerCurrentPwd.setEditable(false);
        tbxCustomerCurrentPwd.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveEditCustomerAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCustomerNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbxCustomerCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxCustomerCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxCustomerNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxCustomerNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxCustomerCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxCustomerCurrentPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxCustomerNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxCustomerNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSaveEditCustomerAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveEditCustomerAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditCustomerAccActionPerformed
        String inputtedUsername = tbxCustomerNewUsername.getText();
        String inputtedPassword = tbxCustomerNewPwd.getText();
        CustomerController customerController = new CustomerController();
        UserController userController = new UserController();
        if(userController.hasUserExisted(inputtedUsername))
        {
            JOptionPane.showMessageDialog(this,"The username has already existed, please try again.");
        }
        else
        {
             customerController.editCustomerAcc(customerId,inputtedUsername,inputtedPassword);
        }
    }//GEN-LAST:event_btnSaveEditCustomerAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new EditCustomerAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveEditCustomerAcc;
    private javax.swing.JLabel lblCustomerCurrentPwd;
    private javax.swing.JLabel lblCustomerCurrentUsername;
    private javax.swing.JLabel lblCustomerNewPwd;
    private javax.swing.JLabel lblCustomerNewUsername;
    private javax.swing.JTextField tbxCustomerCurrentPwd;
    private javax.swing.JTextField tbxCustomerCurrentUsername;
    private javax.swing.JTextField tbxCustomerNewPwd;
    private javax.swing.JTextField tbxCustomerNewUsername;
    // End of variables declaration//GEN-END:variables
}
