package view;

import view.EditManagerAccount;
import view.CreateManager;
import view.Login;
import view.EditTechnicianSelection;
import view.EditCustomerSelection;
import controller.Appt.ApptManagement;
import controller.TechnicianController;
import controller.CustomerController;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ManagerDashboard extends javax.swing.JFrame {
    private int loggedInManagerid;
    /**
     * Creates new form ManagerDashboard
     */
    public ManagerDashboard(int managerId) {
        loggedInManagerid = managerId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditMyAcc = new javax.swing.JButton();
        btnCreateManager = new javax.swing.JButton();
        btnCreateTechnician = new javax.swing.JButton();
        btnEditTechnicianDetails = new javax.swing.JButton();
        btnCreateCustomer = new javax.swing.JButton();
        btnEditCustomerDetails = new javax.swing.JButton();
        apptManagementButton = new javax.swing.JButton();
        btnManagerLogout = new javax.swing.JButton();
        lblLoginUsername1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        setSize(new java.awt.Dimension(0, 0));

        btnEditMyAcc.setText("Edit Manager Account");
        btnEditMyAcc.setPreferredSize(new java.awt.Dimension(200, 200));
        btnEditMyAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMyAccActionPerformed(evt);
            }
        });

        btnCreateManager.setText("Create Manager");
        btnCreateManager.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCreateManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateManagerActionPerformed(evt);
            }
        });

        btnCreateTechnician.setText("Create Technician");
        btnCreateTechnician.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCreateTechnician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTechnicianActionPerformed(evt);
            }
        });

        btnEditTechnicianDetails.setText("Edit Technician Details");
        btnEditTechnicianDetails.setPreferredSize(new java.awt.Dimension(200, 200));
        btnEditTechnicianDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTechnicianDetailsActionPerformed(evt);
            }
        });

        btnCreateCustomer.setText("Create Customer");
        btnCreateCustomer.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });

        btnEditCustomerDetails.setText("Edit Customer Details");
        btnEditCustomerDetails.setPreferredSize(new java.awt.Dimension(200, 200));
        btnEditCustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerDetailsActionPerformed(evt);
            }
        });

        apptManagementButton.setText("Appointment Management");
        apptManagementButton.setPreferredSize(new java.awt.Dimension(200, 200));
        apptManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apptManagementButtonActionPerformed(evt);
            }
        });

        btnManagerLogout.setText("Logout");
        btnManagerLogout.setPreferredSize(new java.awt.Dimension(200, 200));
        btnManagerLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerLogoutActionPerformed(evt);
            }
        });

        lblLoginUsername1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblLoginUsername1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLoginUsername1.setText("APU Hostel Home Appliances Service Centre ");
        lblLoginUsername1.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoginUsername1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCreateManager, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreateTechnician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditTechnicianDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditMyAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(apptManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnManagerLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateCustomer, btnCreateManager, btnCreateTechnician, btnEditCustomerDetails, btnEditMyAcc, btnEditTechnicianDetails});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLoginUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateManager, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditMyAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateTechnician, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTechnicianDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(apptManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnManagerLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {apptManagementButton, btnCreateCustomer, btnCreateManager, btnCreateTechnician, btnEditCustomerDetails, btnEditMyAcc, btnEditTechnicianDetails});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagerLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerLogoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnManagerLogoutActionPerformed

    private void apptManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptManagementButtonActionPerformed
        ApptManagement im = new ApptManagement(loggedInManagerid);
        im.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_apptManagementButtonActionPerformed

    private void btnEditCustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerDetailsActionPerformed
        CustomerController customerController = new CustomerController();
        if(customerController.isCustomerDatabaseEmpty())
        {
            JOptionPane.showMessageDialog(this, "There are no customers available to edit, please create a customer to proceed.");
        }
        else
        {
            EditCustomerSelection editCustomerSelection = new EditCustomerSelection(loggedInManagerid);
            editCustomerSelection.setVisible(true);
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnEditCustomerDetailsActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        CreateCustomer createCustomer = new CreateCustomer(loggedInManagerid);
        createCustomer.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void btnEditTechnicianDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTechnicianDetailsActionPerformed
        TechnicianController technicianController = new TechnicianController();
        if(technicianController.isTechnicianDatabaseEmpty())
        {
            JOptionPane.showMessageDialog(this, "There are no technicians available to edit, please create a technician to proceed.");
        }
        else
        {
            EditTechnicianSelection editTechnicianSelection = new EditTechnicianSelection(loggedInManagerid);
            editTechnicianSelection.setVisible(true);
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnEditTechnicianDetailsActionPerformed

    private void btnCreateTechnicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTechnicianActionPerformed
        CreateTechnician createTechnician = new CreateTechnician(loggedInManagerid);
        createTechnician.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCreateTechnicianActionPerformed

    private void btnCreateManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateManagerActionPerformed
        CreateManager createManager = new CreateManager(loggedInManagerid);
        createManager.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCreateManagerActionPerformed

    private void btnEditMyAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMyAccActionPerformed
        setVisible(false);
        dispose();
        EditManagerAccount editManagerAcc = new EditManagerAccount(loggedInManagerid);
        editManagerAcc.setVisible(true);
    }//GEN-LAST:event_btnEditMyAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apptManagementButton;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnCreateManager;
    private javax.swing.JButton btnCreateTechnician;
    private javax.swing.JButton btnEditCustomerDetails;
    private javax.swing.JButton btnEditMyAcc;
    private javax.swing.JButton btnEditTechnicianDetails;
    private javax.swing.JButton btnManagerLogout;
    private javax.swing.JLabel lblLoginUsername1;
    // End of variables declaration//GEN-END:variables
}
