package view;

import view.EditManagerAccount;
import view.CreateManager;
import view.Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ManagerDashboard extends javax.swing.JFrame {
    private int loggedInManagerid;
    /**
     * Creates new form ManagerDashboard
     */
    public ManagerDashboard(int managerId) {
        loggedInManagerid = managerId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditMyAcc = new javax.swing.JButton();
        btnCreateManager = new javax.swing.JButton();
        btnCreateTechnician = new javax.swing.JButton();
        btnEditTechnicianDetails = new javax.swing.JButton();
        btnCreateCustomer = new javax.swing.JButton();
        btnEditCustomerDetails = new javax.swing.JButton();
        btnManagerLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        btnEditMyAcc.setText("Edit my account");
        btnEditMyAcc.setPreferredSize(new java.awt.Dimension(200, 200));
        btnEditMyAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMyAccActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditMyAcc);

        btnCreateManager.setText("Create Manager");
        btnCreateManager.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCreateManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateManager);

        btnCreateTechnician.setText("Create Technician");
        btnCreateTechnician.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCreateTechnician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTechnicianActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateTechnician);

        btnEditTechnicianDetails.setText("Edit Technician Details");
        btnEditTechnicianDetails.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(btnEditTechnicianDetails);

        btnCreateCustomer.setText("Create Customer");
        btnCreateCustomer.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(btnCreateCustomer);

        btnEditCustomerDetails.setText("Edit Customer Details");
        btnEditCustomerDetails.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(btnEditCustomerDetails);

        btnManagerLogout.setText("Logout");
        btnManagerLogout.setPreferredSize(new java.awt.Dimension(200, 200));
        btnManagerLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnManagerLogout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTechnicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTechnicianActionPerformed
        CreateTechnician createTechnician = new CreateTechnician();
        createTechnician.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCreateTechnicianActionPerformed

    private void btnEditMyAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMyAccActionPerformed
        setVisible(false);
        dispose();
        EditManagerAccount editManagerAcc = new EditManagerAccount(loggedInManagerid);
        editManagerAcc.setVisible(true);
    }//GEN-LAST:event_btnEditMyAccActionPerformed

    private void btnCreateManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateManagerActionPerformed
        CreateManager createManager = new CreateManager();
        createManager.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCreateManagerActionPerformed

    private void btnManagerLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerLogoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnManagerLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnCreateManager;
    private javax.swing.JButton btnCreateTechnician;
    private javax.swing.JButton btnEditCustomerDetails;
    private javax.swing.JButton btnEditMyAcc;
    private javax.swing.JButton btnEditTechnicianDetails;
    private javax.swing.JButton btnManagerLogout;
    // End of variables declaration//GEN-END:variables
}
